from Core.Infrastructure.Specification.SpecificationEvaluator import get_query
from Core.Infrastructure.Specification.Specification import Specification
from Core.Infrastructure.Specification.PagingParam import PagingParams